repos:
  - repo: https://github.com/timothycrosley/isort
    rev: 5.12.0
    hooks:
    -   id: isort
  - repo: https://github.com/psf/black
    rev: 23.3.0
    hooks:
    -   id: black
        args:
          - "--line-length=99"
  - repo: https://github.com/s-weigand/flake8-nb
    rev: v0.5.3
    hooks:
    -   id: flake8-nb
        additional_dependencies: [
            'flake8-bugbear',
            'flake8-comprehensions',
            'flake8-docstrings',
            'flake8-fixme',
            'mccabe',
            'pep8-naming',
        ]
  - repo: https://github.com/PYCQA/flake8
    rev: 6.0.0
    hooks:
    -   id: flake8
        additional_dependencies: [
            'flake8-bugbear==23.3.23',
            'flake8-comprehensions==3.12.0',
            'flake8-docstrings==1.7.0',
            'flake8-fixme==1.1.1',
            'flake8-string-format==0.3.0',
            'mccabe==0.7.0',
            'pep8-naming==0.13.3',
        ]
default_language_version:
    python: python3.9
